sidus_admin:
    configurations:
        publication:
            controller: '%eav.controller%'
            entity: '%sidus_data_class%'
            prefix: /publication
            actions:
                list:
                    path:     /{familyCode}/list
                create:
                    path:     /{familyCode}/create
                    form_type: '%eav_form.type%'
                read:
                    path:     /{familyCode}/read/{id}
                    form_type: '%eav_form.type%'
                edit:
                    path:     /{familyCode}/edit/{id}
                    form_type: '%eav_form.type%'
                delete:
                    path:     /{familyCode}/delete/{id}
            options:
                icon: database
                families:
                    Page: ~
