parameters:
    sidus_data_class: ClientNamespace\EAVModelBundle\Entity\Data
    sidus_value_class: ClientNamespace\EAVModelBundle\Entity\Value

sidus_eav_model:
    data_class: '%sidus_data_class%'
    value_class: '%sidus_value_class%'
    collection_type: sidus_bootstrap_collection
    default_context: {}

imports:
    - { resource: '@CleverAgeEAVManagerAdminBundle/Resources/config/base_config.yml' }
    - { resource: admin.yml }
    - { resource: eav_datagrid.yml }
    - { resource: publishing.yml }

    # Model configuration, order of files matters
    - { resource: project/base.yml }
    - { resource: project/page.yml }
    - { resource: project/user.yml }
    - { resource: variants.yml }
