sidus_eav_data_grid:
    configurations:
        data:
            family: Base
            filter_config:
                sortable:
                    - id
                    - createdAt
                    - updatedAt
                fields: []
            columns:
                id:
                    label: "#"
                label:
                    template: "CleverAgeEAVManagerAdminBundle:Base:clickable.column.html.twig"
                createdAt: ~
                updatedAt: ~
                actions:
                    template: "CleverAgeEAVManagerAdminBundle:Data:list.row.actions.html.twig"
            actions:
                create:
                    form_type: admin_link
                    label: admin.action.create.label
                    action: create
                    icon: plus
                    attr:
                        class: btn-primary
                        data-target: tg_right
            reset_button:
                attr:
                    data-target: tg_center

        # Configuration Example
        page:
            family: Page
            parent: data
            filter_config:
                sortable:
                    - id
                    - title
                    - slug
                    - parentPage
                    - createdAt
                    - updatedAt
                fields:
                    title: ~
                    slug: ~
                    parentPage:
                        type: autocomplete_data
            columns:
                id:
                    label: "#"
                title:
                    template: "CleverAgeEAVManagerAdminBundle:Base:clickable.column.html.twig"
                slug: ~
                parentPage: ~
                createdAt: ~
                updatedAt: ~
                actions:
                    template: "CleverAgeEAVManagerAdminBundle:Data:list.row.actions.html.twig"
