imports:
    - { resource: config.yml }
    - { resource: '@SidusEAVModelBundle/Resources/config/services/annotation_generator.yml' }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: warning
            handler: group
            channels: ['!translation', '!event']
        group:
            type: group
            members:
                - file
                - process
        file:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            max_files: 10
            level: debug
            formatter: monolog.formatter.standard
            channels: ['!cleverage_process_task']
        process:
            type: rotating_file
            path: '%kernel.logs_dir%/process/%kernel.environment%.log'
            max_files: 5
            level: debug
            formatter: monolog.formatter.standard
            channels: ['cleverage_process_task']
        console:
            type: console
            channels: ['!event', '!doctrine', '!cache', '!translation']
