imports:
    - { resource: config.yml }
    - { resource: '@SidusEAVModelBundle/Resources/config/services/annotation_generator.yml' }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        fingers_crossed:
            type: fingers_crossed
            action_level: warning
            handler: file
            channels: ['!cleverage_process', '!cleverage_process_task', '!cleverage_process_transformer', '!translation', '!event']
        file:
            type: rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            max_files: 5
            level: debug
            formatter: monolog.formatter.standard
        process:
            type: rotating_file
            path: '%kernel.logs_dir%/process/%kernel.environment%.log'
            max_files: 5
            level: info
            formatter: monolog.formatter.standard
            channels: ['cleverage_process', 'cleverage_process_task', 'cleverage_process_transformer']
        console:
            type: console
            channels: ['!event', '!doctrine', '!cache', '!translation']
